### ISSUE TITLE
Stack Level too deep with 'Resque'

### ISSUE THREAD

**Issue by kwent** [dipth/Heritage#7]
Hello,

First, thank you for this tool which is very easy to use.

I met a problem with 'Resque' and 'Heritage' -> https://github.com/defunkt/resque

I have a class SoapMonitor which inherites Monitor.

``` ruby

require 'snmp'

class SoapMonitor < ActiveRecord::Base

        attr_accessible :name, :description, :host, :port, :wsdl_filename

        acts_as_heir_of :monitor

        validates_presence_of :name, :host
end
```

A class with a perform method ( Job that worker have to execute)

``` ruby
require 'resque'
require 'soapmonitor'

class Update_SoapMonitor

@queue = :SoapMonitor_queue


        def self.perform(webio_id)
                ActiveRecord::Base.verify_active_connections!
                soapm = SoapMonitor.find(webio_id)
                puts soapm.wsdl_filename #This is OK (Attribute from SoapMonitor)
                puts soapm.host #This is not OK (Attribute from Monitor)
        end

end
```

soapm.host returns me : 

``` ruby
Class
    Update_SoapMonitor
Arguments
    "1"

Exception
    SystemStackError
Error
    stack level too deep

    /usr/lib/ruby/gems/1.8/gems/heritage-0.3.1/lib/heritage/active_record/acts_as_heir.rb:57:in `predecessor_without_build'
    /usr/lib/ruby/gems/1.8/gems/heritage-0.3.1/lib/heritage/active_record/acts_as_heir.rb:58:in `predecessor'
    /usr/lib/ruby/gems/1.8/gems/heritage-0.3.1/lib/heritage/active_record/acts_as_heir.rb:20:in `host'
    /usr/lib/ruby/gems/1.8/gems/savon-0.9.9/lib/savon/client.rb:165:in `send'
    /usr/lib/ruby/gems/1.8/gems/savon-0.9.9/lib/savon/client.rb:165:in `method_missing'
    /var/www/html/MyApp/app/models/soapMonitor.rb:32:in `create_soap_client'
    /usr/lib/ruby/gems/1.8/gems/savon-0.9.9/lib/savon/client.rb:159:in `instance_eval'
    /usr/lib/ruby/gems/1.8/gems/savon-0.9.9/lib/savon/client.rb:159:in `evaluate'
    /usr/lib/ruby/gems/1.8/gems/savon-0.9.9/lib/savon/client.rb:147:in `process'
    /usr/lib/ruby/gems/1.8/gems/savon-0.9.9/lib/savon/client.rb:34:in `initialize'
    /var/www/html/MyApp/app/models/soapMonitor.rb:31:in `new'
    /var/www/html/MyApp/app/models/soapMonitor.rb:31:in `create_soap_client'
    /var/www/html/MyApp/app/models/soapMonitor.rb:80:in `get_value'
    /var/www/html/MyApp/app/models/soapMonitor.rb:41:in `version'
    /var/www/html/MyApp/app/workers/Update_SoapMonitor.rb:28:in `perform'
```

Do you have any suggestions to help me ?

Bests Regards,

**Comment by kwent** [comment]
Issue resolved by switching to 'Heritage' Gem to 'Citier' Gem available at : https://github.com/rexly/citier
